#!/usr/bin/env bash

APP="phoenix_chat" # name of your release

BUILD_HOST="159.203.237.153" # host where to build the release
BUILD_USER="root" # local user at build host
BUILD_AT="/git/phoenix_chat/builds" # build directory on build host
RELEASE_DIR="/git/phoenix_chat/builds/rel/phoenix_chat"
RELEASE_VERSION=0.0.1

STAGING_HOSTS="159.203.237.153" # staging / test hosts separated by space
STAGING_USER="git" # local user at staging hosts
TEST_AT="/test/phoenix_chat" # deploy directory on staging hosts. default is DELIVER_TO

PRODUCTION_HOSTS="159.203.237.153" # deploy / production hosts separated by space
PRODUCTION_USER="root" # local user at deploy hosts
DELIVER_TO="/opt/phoenix_chat" # deploy directory on production hosts

pre_erlang_clean_compile() {
    status "Running phoenix.digest" # log output prepended with "----->"
    __sync_remote " # runs the commands on the build host
      [ -f ~/.profile ] && source ~/.profile # load profile (optional)
      set -e # fail if any command fails (recommended)
      cd '$BUILD_AT' # enter the build directory on the build host (required)
      # prepare something
      mkdir -p priv/static # required by the phoenix.digest task
      # run your custom task
      APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phoenix.digest $SILENCE
    "
  }
